name: License scan on PR

on: 
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  schedule:
    - cron: '33 10 * * 4'
  push:
    branches: [ "main" ]

jobs:
  compliance_check:
    runs-on: ubuntu-latest
    name: Perform license scan
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: License check
      id: compliance
      continue-on-error: true
      uses: fossology/fossology-action@v1
      with:
        scan_mode: 'repo'
        scanners: 'copyright'
        report_format: 'SPDX_YAML'

    - name: Upload Scan Results Artifact
      uses: actions/upload-artifact@v4
      with:
          name: Fossology scan results
          path: results/
